package org.mule.modules.samples;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName="DynamoDbConnectorTestTable_toDelete")
public class FakeCustomer {

    private String num; // Only String typed keys can use the @DynamoDBAutoGeneratedKey annotation
    private String name;
    private String notes;
    private String phone;

    public FakeCustomer() {}

    public FakeCustomer (String num, String name, String notes, String phone) {
        setNum(num);
        setName(name);
        setNotes(notes);
        setPhone(phone);
    }

    public static FakeCustomer copy(FakeCustomer fakeCustomer) {
        return new FakeCustomer(
                fakeCustomer.getNum(),
                fakeCustomer.getName(),
                fakeCustomer.getNotes(),
                fakeCustomer.getPhone());
    }

    @DynamoDBHashKey(attributeName = "num")
    @DynamoDBAutoGeneratedKey
    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    @DynamoDBAttribute(attributeName="name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBHashKey(attributeName="phone")
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }


    @DynamoDBRangeKey(attributeName="notes")
    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }


    @Override
    public boolean equals(Object o) {
        // checks to see if the two operands point to the same object (does not verify if they are equivalent)
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        FakeCustomer fakeCustomer = (FakeCustomer) o;

        if (num != null ? !num.equals(fakeCustomer.num) : fakeCustomer.num != null)
            return false;
        if (name != null ? !name.equals(fakeCustomer.name) : fakeCustomer.name != null)
            return false;
        if (phone != null ? !phone.equals(fakeCustomer.phone) : fakeCustomer.phone != null)
            return false;
        if (notes != null ? !notes.equals(fakeCustomer.notes) : fakeCustomer.notes != null)
            return false;

        return true;
    }

    /**
     * Check if another copy of FakeCustomer is equal, ignoring the 'num' value
     *
     * 'num' is automatically generated.  When exercising acceptance tests, we do not know the value that it will
     * be assigned.  This method was created to compare the key data inside request/response tests.
     *
     * @param o
     *          the object, of type FakeCustomer, to compare with
     * @return
     *          true: if everything but 'num' is equal, false if otherwise
     */
    public boolean equals_IgnoreNumValue(Object o) {
        // checks to see if the two operands point to the same object (does not verify if they are equivalent)
        if (this == o) return true;

        if (o == null || getClass() != o.getClass()) return false;

        FakeCustomer fakeCustomer = (FakeCustomer) o;

        if (name != null ? !name.equals(fakeCustomer.name) : fakeCustomer.name != null)
            return false;
        if (phone != null ? !phone.equals(fakeCustomer.phone) : fakeCustomer.phone != null)
            return false;
        if (notes != null ? !notes.equals(fakeCustomer.notes) : fakeCustomer.notes != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = num != null ? num.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (phone != null ? phone.hashCode() : 0);
        result = 31 * result + (notes != null ? notes.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "FakeCustomer {" +
                "num='" + getNum() + '\'' +
                ", name='" + getName() + '\'' +
                ", phone='" + getPhone() + '\'' +
                ", notes='" + getNotes() + '\'' +
                '}';
    }
}